# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 237)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:#0e2a36;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 137, 19))
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(0, 20, 159, 19))
        self.password_label.setStyleSheet("color:white;")
        self.password_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.password_label.setObjectName("password_label")
        self.numbers_chek = QtWidgets.QCheckBox(self.centralwidget)
        self.numbers_chek.setGeometry(QtCore.QRect(0, 40, 196, 23))
        self.numbers_chek.setStyleSheet("color:white;\n"
"")
        self.numbers_chek.setObjectName("numbers_chek")
        self.symbol_chek = QtWidgets.QCheckBox(self.centralwidget)
        self.symbol_chek.setGeometry(QtCore.QRect(0, 60, 215, 23))
        self.symbol_chek.setStyleSheet("color:white;")
        self.symbol_chek.setObjectName("symbol_chek")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(70, 140, 95, 43))
        self.generate_btn.setStyleSheet("background-color: #26878c;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius: 15px")
        self.generate_btn.setObjectName("generate_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 251, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор паролів"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.password_label.setText(_translate("MainWindow", "Згенерований пароль"))
        self.numbers_chek.setText(_translate("MainWindow", "Використовувати числа"))
        self.symbol_chek.setText(_translate("MainWindow", "Використовувати символи"))
        self.generate_btn.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
